<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PHY_LIB</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DSharpPlus" Version="4.5.3" />
    <PackageReference Include="DSharpPlus.CommandsNext" Version="4.5.3" />
  </ItemGroup>

</Project>
